[package]
name = "asus-linux-fan-mode-notification"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libappindicator = "0.9.0"
notify-rust = "4.10.0"
